music_directory "~/Music"
playlist_directory "~/.local/share/mpd/playlists"
db_file "~/.local/share/mpd/mpd.db"
log_file "~/.local/share/mpd/mpd.log"
pid_file "~/.cache/mpd/mpd.pid"
# cache_dir "~/.cache/mpd/"
state_file "~/.local/share/mpd/state"
sticker_file "~/.local/share/mpd/sticker.db"

bind_to_address "~/.local/share/mpd/socket"
port "6600"

audio_output {
    type "pipewire"
    name "Pipewire Playback"
}
