profile {
    time = 6:00
    identity = true
}

profile {
    time = 18:00
    temperature = 5000
}

profile {
    time = 20:00
    temperature = 3500
    gamma = 0.9
}

profile {
    time = 22:00
    temperature = 2000
    gamma = 0.8
}

profile {
    time = 0:00
    temperature = 1000
    gamma = 0.75
}