
background {
    path =  screenshot
    blur_passes = 3
    blur_size = 3
    brightness = 1.48
    vibrancy = 1
    vibrancy_darkness = 1

    # color = rgba(220, 146, 172, 1)
    # color = rgba(139, 104, 195, 1)
    color = rgba(141, 169, 207, 1)

}


animations {
    enabled = true

    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
    bezier = linear, 1, 1, 0, 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = hiiiii :)
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    hide_input = true

    position = 0, -20
    halign = center
    valign = center
}


# 2k 27" monitor section
# TIME
label {
    monitor = HDMI-A-1
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = 0, 20%
    halign = center
    valign = center

    shadow_passes = 1
}

# DATE
label {
    monitor = HDMI-A-1
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 25
    font_family = $font

    position = 0, 27%
    halign = center
    valign = center

    shadow_passes = 1
}

# LAYOUT
label {
    monitor = HDMI-A-1
    text = $LAYOUT[en,ru]
    font_size = 24
    onclick = hyprctl switchxkblayout all next

    position = 8.8%, -20
    halign = center
    valign = center

    shadow_passes = 1
}

auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}


# Laptop monitor section
# TIME
label {
    monitor = eDP-1
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 71
    font_family = $font

    position = 0, 20%
    halign = center
    valign = center

    shadow_passes = 1
}

# DATE
label {
    monitor = eDP-1
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 19.75
    font_family = $font

    position = 0, 27%
    halign = center
    valign = center

    shadow_passes = 1
}

# LAYOUT
label {
    monitor = eDP-1
    text = $LAYOUT[en,ru]
    font_size = 19
    onclick = hyprctl switchxkblayout all next

    position = 8.8%, -20
    halign = center
    valign = center

    shadow_passes = 1
}